import csv
fieldnames = ['id', 'name', 'age', 'height', 'weight', 'gender']
rows = [
    {'id': 1,
    'name': 'Pedro',
    'age': 20,
    'height': 1.76,
    'weight': 74,
    'gender': 'male'},
    {'id': 2,
    'name': 'Jamal',
    'age': 23,
    'height': 1.98,
    'weight': 98,
    'gender': 'male'},
    {'id': 3,
    'name': 'Speed',
    'age': 17,
    'height': 1.72,
    'weight': 64,
    'gender': 'male'},
    {'id': 4,
    'name': 'Alexa',
    'age': 26,
    'height': 1.68,
    'weight': 55,
    'gender': 'female'},
    {'id': 5,
    'name': 'Eivor',
    'age': 24,
    'height': 1.85,
    'weight': 80,
    'gender': 'female'},
    {'id': 6,
    'name': 'John',
    'age': 46,
    'height': 1.70,
    'weight': 101,
    'gender': 'male'},
    {'id': 7,
    'name': 'Robert',
    'age': 20,
    'height': 1.70,
    'weight': 63,
    'gender': 'male'},
    {'id': 8,
    'name': 'Eric',
    'age': 26,
    'height': 1.82,
    'weight': 70,
    'gender': 'male'},
    {'id': 9,
    'name': 'Sigurd',
    'age': 30,
    'height': 1.76,
    'weight': 74,
    'gender': 'male'},
    {'id': 10,
    'name': 'Darcy',
    'age': 56,
    'height': 1.63,
    'weight': 52,
    'gender': 'female'
    }
]

with open('names.csv', 'w', encoding='UTF8', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)
